# Generated by Django 5.1.1 on 2024-09-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_alter_food_category_alter_food_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='transaction_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodscategory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodscategory',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodscategory',
            name='transaction_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
