# Generated by Django 5.1.1 on 2024-09-09 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_food_foods_name_01bd69_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodscategory',
            options={'verbose_name_plural': 'Food categories'},
        ),
    ]
