# Generated by Django 5.1.1 on 2024-09-05 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderitem',
            table='order_items',
        ),
    ]
