# Generated by Django 5.1.1 on 2024-09-05 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='longtitude',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='author',
            new_name='user',
        ),
    ]
