# Generated by Django 5.1.1 on 2024-09-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_deleted_order_deleted_by_cascade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('accepted', 'Accepted'), ('sent', 'Sent'), ('completed', 'Completed')], default='ordered', max_length=50),
        ),
    ]
