# Generated by Django 5.1.1 on 2024-09-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_delete_ordertest_order_orders_status_762191_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cooked_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('accepted', 'Accepted'), ('cooking', 'Cooking'), ('sent', 'Sent'), ('completed', 'Completed')], default='ordered', max_length=50),
        ),
    ]
