version: '3.9'

services:
  backend:
    container_name: fastfood_backend
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app/
    ports:
      - 5000:8000
    env_file:
      - .env
    networks:
      - fastfood_net

networks:
  fastfood_net: