# Generated by Django 5.1.1 on 2024-09-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foods', '0002_alter_food_category_alter_food_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longtitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('food', models.ManyToManyField(to='foods.food')),
            ],
            options={
                'db_table': 'fast_foods',
            },
        ),
    ]
