# Generated by Django 5.1.1 on 2024-09-05 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fastfood',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
