# Generated by Django 5.1.1 on 2024-09-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoods', '0002_rename_longtitude_fastfood_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastfood',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fastfood',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fastfood',
            name='transaction_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
