# Generated by Django 5.1.1 on 2024-09-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoods', '0003_fastfood_deleted_at_fastfood_restored_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fastfood',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='fastfood',
            name='restored_at',
        ),
        migrations.RemoveField(
            model_name='fastfood',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='fastfood',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='fastfood',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
