# Generated by Django 5.1.1 on 2024-09-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoods', '0004_remove_fastfood_deleted_at_and_more'),
        ('foods', '0006_food_foods_name_01bd69_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fastfood',
            index=models.Index(fields=['name'], name='fast_foods_name_4fbbea_idx'),
        ),
    ]
